export const languageOptions = [
    {
      id: 63,
      name: "js",
      label: "JavaScript (Node.js 20.3.0)",
      value: "Javascript",
    },
    // {
    //   id: 45,
    //   name: "Assembly (NASM 2.16.01)",
    //   label: "Assembly (NASM 2.16.01)",
    //   value: "assembly",
    // },
    // {
    //   id: 46,
    //   name: "Bash (5.1.16)",
    //   label: "Bash (5.1.16)",
    //   value: "bash",
    // },
    // {
    //   id: 47,
    //   name: "Basic (FBC 1.09.0)",
    //   label: "Basic (FBC 1.09.0)",
    //   value: "basic",
    // },
    // {
    //   id: 48,
    //   name: "C (GCC 12.2.0)",
    //   label: "C (GCC 12.2.0)",
    //   value: "c",
    // },
    // {
    //   id: 49,
    //   name: "C# (Mono 6.12.0.182)",
    //   label: "C# (Mono 6.12.0.182)",
    //   value: "csharp",
    // },
    {
      id: 50,
      name: "cpp",
      label: "C++ (GCC 12.2.0)",
      value: "C++",
    },
    // {
    //   id: 51,
    //   name: "Clojure (1.11.1)",
    //   label: "Clojure (1.11.1)",
    //   value: "clojure",
    // },
    // {
    //   id: 52,
    //   name: "COBOL (GnuCOBOL 3.1.2)",
    //   label: "COBOL (GnuCOBOL 3.1.2)",
    //   value: "cobol",
    // },
    // {
    //   id: 53,
    //   name: "Common Lisp (SBCL 2.2.8)",
    //   label: "Common Lisp (SBCL 2.2.8)",
    //   value: "commonlisp",
    // },
    // {
    //   id: 54,
    //   name: "D (DMD 2.104.0)",
    //   label: "D (DMD 2.104.0)",
    //   value: "d",
    // },
    // {
    //   id: 55,
    //   name: "Elixir (1.14.4)",
    //   label: "Elixir (1.14.4)",
    //   value: "elixir",
    // },
    // {
    //   id: 56,
    //   name: "Erlang (OTP 25.2)",
    //   label: "Erlang (OTP 25.2)",
    //   value: "erlang",
    // },
    // {
    //   id: 57,
    //   name: "Fortran (GFortran 12.2.0)",
    //   label: "Fortran (GFortran 12.2.0)",
    //   value: "fortran",
    // },
    // {
    //   id: 58,
    //   name: "Go (1.20.4)",
    //   label: "Go (1.20.4)",
    //   value: "go",
    // },
    // {
    //   id: 59,
    //   name: "Haskell (GHC 9.2.5)",
    //   label: "Haskell (GHC 9.2.5)",
    //   value: "haskell",
    // },
    // {
    //   id: 60,
    //   name: "Java (OpenJDK 20.0.1)",
    //   label: "Java (OpenJDK 20.0.1)",
    //   value: "java",
    // },
    // {
    //   id: 61,
    //   name: "Kotlin (1.8.21)",
    //   label: "Kotlin (1.8.21)",
    //   value: "kotlin",
    // },
    // {
    //   id: 62,
    //   name: "Lua (5.4.6)",
    //   label: "Lua (5.4.6)",
    //   value: "lua",
    // },
    // {
    //   id: 64,
    //   name: "Objective-C (Clang 15.0.7)",
    //   label: "Objective-C (Clang 15.0.7)",
    //   value: "objectivec",
    // },
    // {
    //   id: 65,
    //   name: "OCaml (5.1.0)",
    //   label: "OCaml (5.1.0)",
    //   value: "ocaml",
    // },
    // {
    //   id: 66,
    //   name: "Octave (8.2.0)",
    //   label: "Octave (8.2.0)",
    //   value: "octave",
    // },
    // {
    //   id: 67,
    //   name: "Pascal (FPC 3.2.2)",
    //   label: "Pascal (FPC 3.2.2)",
    //   value: "pascal",
    // },
    // {
    //   id: 68,
    //   name: "Perl (5.36.0)",
    //   label: "Perl (5.36.0)",
    //   value: "perl",
    // },
    // {
    //   id: 69,
    //   name: "PHP (8.2.5)",
    //   label: "PHP (8.2.5)",
    //   value: "php",
    // },
    // {
    //   id: 70,
    //   name: "Prolog (GNU Prolog 1.5.0)",
    //   label: "Prolog (GNU Prolog 1.5.0)",
    //   value: "prolog",
    // },
    // {
    //   id: 71,
    //   name: "Python (3.11.3)",
    //   label: "Python (3.11.3)",
    //   value: "python",
    // },
    // {
    //   id: 72,
    //   name: "R (4.3.0)",
    //   label: "R (4.3.0)",
    //   value: "r",
    // },
    // {
    //   id: 73,
    //   name: "Ruby (3.2.2)",
    //   label: "Ruby (3.2.2)",
    //   value: "ruby",
    // },
    {
      id: 74,
      name: "rs",
      label: "Rust (1.69.0)",
      value: "Rust",
    },
  //   {
  //     id: 75,
  //     name: "Scala (3.3.0)",
  //     label: "Scala (3.3.0)",
  //     value: "scala",
  //   },
  //   {
  //     id: 76,
  //     name: "Scheme (Gauche 0.9.13)",
  //     label: "Scheme (Gauche 0.9.13)",
  //     value: "scheme",
  //   },
  //   {
  //     id: 77,
  //     name: "Swift (5.8.1)",
  //     label: "Swift (5.8.1)",
  //     value: "swift",
  //   },
  //   {
  //     id: 78,
  //     name: "TypeScript (5.1.3)",
  //     label: "TypeScript (5.1.3)",
  //     value: "typescript",
  //   },
  //   {
  //     id: 79,
  //     name: "Visual Basic (vbnc 0.0.0.5943)",
  //     label: "Visual Basic (vbnc 0.0.0.5943)",
  //     value: "vbnet",
  //   },
  //   {
  //     id: 80,
  //     name: "F# (5.0.202)",
  //     label: "F# (5.0.202)",
  //     value: "fsharp",
  //   },
  //   {
  //     id: 81,
  //     name: "Racket (8.8)",
  //     label: "Racket (8.8)",
  //     value: "racket",
  //   },
  // ];
]