name: Boilerplate Generator

on:
  push:
    paths:
      - 'problems/**'

jobs:
  run-boilerplate-generator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: ./boilerplateGenerator

    - name: Determine changed directories
      id: changes
      run: |
        changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} problems | cut -d/ -f2 | sort | uniq)
        echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV

    - name: Run boilerplate generator
      env:
        GENERATOR_FILE_PATHS: ${{ env.changed_dirs }}
      run: node ./index.js
      working-directory: ./boilerplateGenerator

    - name: Add changes to Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
      working-directory: ./boilerplateGenerator

    - name: Commit changes
      run: |
        git commit -m "Add boilerplate code for problems: ${{ env.changed_dirs }}"
      working-directory: ./boilerplateGenerator
      if: success()

    - name: Push changes
      run: git push
      working-directory: ./boilerplateGenerator
      if: success()
